Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : exercicio 6
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2022
Var
// Seção de Declarações das variáveis 
sal, salreceber,grat, imp: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
LEIA (sal)
grat <- sal * 5/100
imp <- sal * 7/100
salreceber <- sal + grat - imp
ESCREVA ("salreceber")

Fimalgoritmo